version: '3.9'
services:
  prepper-app:
    build:
      context: .
      file: Containerfile
    container_name: prepper-app
    ports:
      - "3000:3000"
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data.sqlite
      - VLLM_MODEL_PATH=./models/llm
      - APP_PASSPHRASE=${APP_PASSPHRASE:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    restart: unless-stopped
